baseURL = "https://docs.pirsch.io/"
languageCode = "en"
title = "Pirsch Documentation"
theme = "seeker"

[menu]
    [[menu.main]]
        name = "Log in"
        url = "https://pirsch.io/login"
        weight = 1
    [[menu.main]]
        name = "Get Started"
        url = "https://pirsch.io/signup"
        weight = 2
    [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/pirsch-analytics/docs"
        weight = 1
    [[menu.footer]]
        name = "Terms"
        url = "https://pirsch.io/terms"
        weight = 2
    [[menu.footer]]
        name = "Privacy"
        url = "https://pirsch.io/privacy"
        weight = 3
    [[menu.footer]]
        name = "Legal"
        url = "https://pirsch.io/legal"
        weight = 4

[params]
    title = "Pirsch Docs"
    copyright = "© 2021 Emvi Software GmbH"
    url = "https://emvi.com"
    titleColor = "#ffffff"
    themeColor = "#000000"
    twitter = "@PirschAnalytics"
    twitterCard = "product"
    pirsch = "6V8bSjEHJ19PK2hVxaaqJhItHUpSUekW"

[outputFormats.SearchIndex]
    baseName = "search"
    mediaType = "application/json"

[outputs]
    home = ["HTML", "RSS", "SearchIndex"]

[markup]
    [markup.highlight]
        linenos = true
        noClasses = false
