baseURL = "https://docs.pirsch.io/"
languageCode = "en"
title = "Pirsch Documentation"
theme = "seeker"

[menu]
    [[menu.main]]
        name = "Website"
        url = "https://pirsch.io/"
        weight = 1
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/pirsch-analytics/docs"
        weight = 2
    [[menu.footer]]
        name = "Terms"
        url = "https://pirsch.io/terms"
        weight = 1
    [[menu.footer]]
        name = "Privacy"
        url = "https://pirsch.io/privacy"
        weight = 2
    [[menu.footer]]
        name = "Legal"
        url = "https://pirsch.io/legal"
        weight = 3

[params]
    title = "Pirsch Docs"
    copyright = "© 2020 Emvi Software GmbH"
    url = "https://emvi.com"

[outputFormats.SearchIndex]
    baseName = "search"
    mediaType = "application/json"

[outputs]
    home = ["HTML", "RSS", "SearchIndex"]

[markup]
    [markup.highlight]
        linenos = true
        noClasses = false
