baseURL = "https://docs.pirsch.io/"
languageCode = "en"
title = "Pirsch Documentation"
theme = "seeker"

[menu]
    [[menu.main]]
        name = "Website"
        url = "https://pirsch.io/"
        weight = 1
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/pirsch-analytics/docs"
        weight = 2
    [[menu.footer]]
        name = "Website"
        url = "https://pirsch.io/"
        weight = 1
    [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/pirsch-analytics/docs"
        weight = 2
    [[menu.footer]]
        name = "Privacy"
        url = "https://pirsch.io/privacy"
        weight = 3
    [[menu.footer]]
        name = "Legal"
        url = "https://pirsch.io/legal"
        weight = 4

[params]
    copyright = "© 2020 Emvi Software GmbH"
